scan_filter_chain:

- name: box_filter_right_1
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: .inf
    max_y: -0.5
    max_z: .inf
    min_x: -.inf
    min_y: -.inf
    min_z: -.inf

- name: box_filter_right_2
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: .inf
    max_y: .inf
    max_z: .inf
    min_x: -.inf
    min_y: -0.25
    min_z: -.inf

-  name: box_filter_right_front
   type: laser_filters/LaserScanBoxFilter
   params:
    box_frame: base_link
    max_x: .inf
    max_y: .inf
    max_z: .inf
    min_x: 3.75
    min_y: -.inf
    min_z: -.inf
