//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the fieldrobot_05 package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __fieldrobot_05__LIDAR_ROW_EXTRACTOR_PARAMSCONFIG_H__
#define __fieldrobot_05__LIDAR_ROW_EXTRACTOR_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace fieldrobot_05
{
  class lidar_row_extractor_paramsConfigStatics;
  
  class lidar_row_extractor_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(lidar_row_extractor_paramsConfig &config, const lidar_row_extractor_paramsConfig &max, const lidar_row_extractor_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const lidar_row_extractor_paramsConfig &config1, const lidar_row_extractor_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, lidar_row_extractor_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const lidar_row_extractor_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, lidar_row_extractor_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const lidar_row_extractor_paramsConfig &config) const = 0;
      virtual void getValue(const lidar_row_extractor_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T lidar_row_extractor_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (lidar_row_extractor_paramsConfig::* field);

      virtual void clamp(lidar_row_extractor_paramsConfig &config, const lidar_row_extractor_paramsConfig &max, const lidar_row_extractor_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const lidar_row_extractor_paramsConfig &config1, const lidar_row_extractor_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, lidar_row_extractor_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const lidar_row_extractor_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, lidar_row_extractor_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const lidar_row_extractor_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const lidar_row_extractor_paramsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, lidar_row_extractor_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, lidar_row_extractor_paramsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<lidar_row_extractor_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(lidar_row_extractor_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("laser_scan_max_distance"==(*_i)->name){laser_scan_max_distance = boost::any_cast<double>(val);}
        if("inliers_epsilon"==(*_i)->name){inliers_epsilon = boost::any_cast<double>(val);}
        if("ransac_n"==(*_i)->name){ransac_n = boost::any_cast<int>(val);}
        if("box_lim_x"==(*_i)->name){box_lim_x = boost::any_cast<double>(val);}
        if("box_lim_y"==(*_i)->name){box_lim_y = boost::any_cast<double>(val);}
        if("headland_box_min_x"==(*_i)->name){headland_box_min_x = boost::any_cast<double>(val);}
        if("headland_box_max_x"==(*_i)->name){headland_box_max_x = boost::any_cast<double>(val);}
        if("headland_box_lim_y"==(*_i)->name){headland_box_lim_y = boost::any_cast<double>(val);}
        if("ransac_minimum_distance_fit"==(*_i)->name){ransac_minimum_distance_fit = boost::any_cast<double>(val);}
        if("ransac_maximum_distance_fit"==(*_i)->name){ransac_maximum_distance_fit = boost::any_cast<double>(val);}
        if("minimum_inliers"==(*_i)->name){minimum_inliers = boost::any_cast<double>(val);}
      }
    }

    double laser_scan_max_distance;
double inliers_epsilon;
int ransac_n;
double box_lim_x;
double box_lim_y;
double headland_box_min_x;
double headland_box_max_x;
double headland_box_lim_y;
double ransac_minimum_distance_fit;
double ransac_maximum_distance_fit;
double minimum_inliers;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double laser_scan_max_distance;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double inliers_epsilon;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int ransac_n;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double box_lim_x;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double box_lim_y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double headland_box_min_x;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double headland_box_max_x;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double headland_box_lim_y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ransac_minimum_distance_fit;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ransac_maximum_distance_fit;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double minimum_inliers;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("lidar_row_extractor_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const lidar_row_extractor_paramsConfig &__max__ = __getMax__();
      const lidar_row_extractor_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const lidar_row_extractor_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const lidar_row_extractor_paramsConfig &__getDefault__();
    static const lidar_row_extractor_paramsConfig &__getMax__();
    static const lidar_row_extractor_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const lidar_row_extractor_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void lidar_row_extractor_paramsConfig::ParamDescription<std::string>::clamp(lidar_row_extractor_paramsConfig &config, const lidar_row_extractor_paramsConfig &max, const lidar_row_extractor_paramsConfig &min) const
  {
    return;
  }

  class lidar_row_extractor_paramsConfigStatics
  {
    friend class lidar_row_extractor_paramsConfig;
    
    lidar_row_extractor_paramsConfigStatics()
    {
lidar_row_extractor_paramsConfig::GroupDescription<lidar_row_extractor_paramsConfig::DEFAULT, lidar_row_extractor_paramsConfig> Default("Default", "", 0, 0, true, &lidar_row_extractor_paramsConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.laser_scan_max_distance = 0.1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.laser_scan_max_distance = 20.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.laser_scan_max_distance = 4.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("laser_scan_max_distance", "double", 0, "The distance the laser looks ahead", "", &lidar_row_extractor_paramsConfig::laser_scan_max_distance)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("laser_scan_max_distance", "double", 0, "The distance the laser looks ahead", "", &lidar_row_extractor_paramsConfig::laser_scan_max_distance)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.inliers_epsilon = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.inliers_epsilon = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.inliers_epsilon = 0.1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("inliers_epsilon", "double", 0, "The the ratio between inliers and outliers before ransac terminates", "", &lidar_row_extractor_paramsConfig::inliers_epsilon)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("inliers_epsilon", "double", 0, "The the ratio between inliers and outliers before ransac terminates", "", &lidar_row_extractor_paramsConfig::inliers_epsilon)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ransac_n = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ransac_n = 100000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ransac_n = 100;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<int>("ransac_n", "int", 0, "Number of ransac iterations", "", &lidar_row_extractor_paramsConfig::ransac_n)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<int>("ransac_n", "int", 0, "Number of ransac iterations", "", &lidar_row_extractor_paramsConfig::ransac_n)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.box_lim_x = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.box_lim_x = 20.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.box_lim_x = 2.3;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("box_lim_x", "double", 0, "Look forward maximum distance", "", &lidar_row_extractor_paramsConfig::box_lim_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("box_lim_x", "double", 0, "Look forward maximum distance", "", &lidar_row_extractor_paramsConfig::box_lim_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.box_lim_y = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.box_lim_y = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.box_lim_y = 1.4;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("box_lim_y", "double", 0, "Look side maximum distance", "", &lidar_row_extractor_paramsConfig::box_lim_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("box_lim_y", "double", 0, "Look side maximum distance", "", &lidar_row_extractor_paramsConfig::box_lim_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.headland_box_min_x = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.headland_box_min_x = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.headland_box_min_x = 0.9;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("headland_box_min_x", "double", 0, "Look forward headland minimum distance", "", &lidar_row_extractor_paramsConfig::headland_box_min_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("headland_box_min_x", "double", 0, "Look forward headland minimum distance", "", &lidar_row_extractor_paramsConfig::headland_box_min_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.headland_box_max_x = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.headland_box_max_x = 5.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.headland_box_max_x = 1.1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("headland_box_max_x", "double", 0, "Look forward headland maximum distance", "", &lidar_row_extractor_paramsConfig::headland_box_max_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("headland_box_max_x", "double", 0, "Look forward headland maximum distance", "", &lidar_row_extractor_paramsConfig::headland_box_max_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.headland_box_lim_y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.headland_box_lim_y = 5.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.headland_box_lim_y = 1.6;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("headland_box_lim_y", "double", 0, "Look side headland lim distance", "", &lidar_row_extractor_paramsConfig::headland_box_lim_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("headland_box_lim_y", "double", 0, "Look side headland lim distance", "", &lidar_row_extractor_paramsConfig::headland_box_lim_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ransac_minimum_distance_fit = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ransac_minimum_distance_fit = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ransac_minimum_distance_fit = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("ransac_minimum_distance_fit", "double", 0, "the min distance between random points selected for fitting", "", &lidar_row_extractor_paramsConfig::ransac_minimum_distance_fit)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("ransac_minimum_distance_fit", "double", 0, "the min distance between random points selected for fitting", "", &lidar_row_extractor_paramsConfig::ransac_minimum_distance_fit)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ransac_maximum_distance_fit = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ransac_maximum_distance_fit = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ransac_maximum_distance_fit = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("ransac_maximum_distance_fit", "double", 0, "the max distance between random points selected for fitting", "", &lidar_row_extractor_paramsConfig::ransac_maximum_distance_fit)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("ransac_maximum_distance_fit", "double", 0, "the max distance between random points selected for fitting", "", &lidar_row_extractor_paramsConfig::ransac_maximum_distance_fit)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.minimum_inliers = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.minimum_inliers = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.minimum_inliers = 0.4;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("minimum_inliers", "double", 0, "Minimum number of inliers before ransac terminates", "", &lidar_row_extractor_paramsConfig::minimum_inliers)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr(new lidar_row_extractor_paramsConfig::ParamDescription<double>("minimum_inliers", "double", 0, "Minimum number of inliers before ransac terminates", "", &lidar_row_extractor_paramsConfig::minimum_inliers)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(lidar_row_extractor_paramsConfig::AbstractGroupDescriptionConstPtr(new lidar_row_extractor_paramsConfig::GroupDescription<lidar_row_extractor_paramsConfig::DEFAULT, lidar_row_extractor_paramsConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<lidar_row_extractor_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<lidar_row_extractor_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    lidar_row_extractor_paramsConfig __max__;
    lidar_row_extractor_paramsConfig __min__;
    lidar_row_extractor_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const lidar_row_extractor_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static lidar_row_extractor_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &lidar_row_extractor_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const lidar_row_extractor_paramsConfig &lidar_row_extractor_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const lidar_row_extractor_paramsConfig &lidar_row_extractor_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const lidar_row_extractor_paramsConfig &lidar_row_extractor_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<lidar_row_extractor_paramsConfig::AbstractParamDescriptionConstPtr> &lidar_row_extractor_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<lidar_row_extractor_paramsConfig::AbstractGroupDescriptionConstPtr> &lidar_row_extractor_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const lidar_row_extractor_paramsConfigStatics *lidar_row_extractor_paramsConfig::__get_statics__()
  {
    const static lidar_row_extractor_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = lidar_row_extractor_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __LIDAR_ROW_EXTRACTOR_PARAMSRECONFIGURATOR_H__
